[package]
name = "Tarner-Monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
iced = { version = "0.12.1", features = ["tokio"] } 
sysinfo = "0.37.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
tokio = { version = "1.48.0", features = ["time"] }
